name: Hitman
version: '${project.version}'
main: io.github.sawors.hitman.Hitman
api-version: 1.18
depend: [ Citizens ]
authors: [ Sawors ]
commands:
  setrole:
    description: uwu
  creategame:
    description: uwu
  giveitem:
    description: uwu